disabled_rules:
  - trailing_whitespace
  - line_length
  - todo

opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message

included:
  - Core
  - Views
  - Models
  - Services
  - Utils

excluded:
  - Pods
  - Carthage
  - Docs

line_length:
  warning: 120
  error: 160

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - x
    - y
    - to
